genrule(
    name = "copy_role",
    srcs = ["//api/v1alpha1:generated.rbac"],
    outs = ["role.yaml"],
    cmd = "cp $< $@",
    visibility = ["//visibility:public"],
)

exports_files([
    "deployment.yaml",
    "honeypot-secret.yaml",
    "rolebinding.yaml",
    "serviceaccount.yaml",
    "_helpers.tpl",
    "gatewayclass.yaml",
    "vpa.yaml",
    "vpa-crd.yaml",
    "vpa-rbac.yaml",
    "vpa-controllers.yaml",
    "vpa-certs.yaml",
])

filegroup(
    name = "templates",
    srcs = glob(["*.yaml"]) + [":copy_role"],
    visibility = ["//visibility:public"],
)
